steps:
- emerge -b =\${PACKAGE_CATEGORY}/\${PACKAGE_NAME}-\${PACKAGE_VERSION}
requires:
- category: "layer"
  version:  ">=0.1"
  name:     "build-sabayon-overlays"

includes:
- /usr/portage/packages/.*
