steps:
- emerge -b =sys-power/acpi_call-${PACKAGE_VERSION}
requires:
- category: "sys-kernel"
  version:  "4.14.105"
  name:     "linux-sabayon"
- category: "sys-kernel"
  version:  "4.14.105"
  name:     "sabayon-sources"

includes:
- /usr/portage/packages/.*
