steps:
- emerge -b =${GENTOO_CATEGORY}/vhba-${GENTOO_VERSION}

- cd /usr/portage/packages/${GENTOO_CATEGORY}
- mv vhba-${GENTOO_VERSION}.tbz2 vhba-${PACKAGE_VERSION}.tbz2

env:
- "GENTOO_VERSION=20190410"
- "GENTOO_CATEGORY=sys-fs"
requires:
- category: "sys-kernel"
  version:  "4.4.178"
  name:     "linux-sabayon"
- category: "sys-kernel"
  version:  "4.4.178"
  name:     "sabayon-sources"

includes:
- /usr/portage/packages/.*

