steps:
- emerge -b =sys-power/bbswitch-${PACKAGE_VERSION}
requires:
- category: "sys-kernel"
  version:  "4.9.111"
  name:     "linux-sabayon"
- category: "sys-kernel"
  version:  "4.9.111"
  name:     "sabayon-sources"

includes:
- /usr/portage/packages/.*
