steps:
- emerge -b =net-firewall/rtsp-conntrack-${PACKAGE_VERSION}
requires:
- category: "sys-kernel"
  version:  "5.3.1"
  name:     "linux-sabayon"
- category: "sys-kernel"
  version:  "5.3.1"
  name:     "sabayon-sources"

includes:
- /usr/portage/packages/.*
