steps:
- emerge -b =x11-drivers/nvidia-drivers-${PACKAGE_VERSION}
requires:
- category: "sys-kernel"
  version:  "4.9.197"
  name:     "linux-sabayon"
- category: "sys-kernel"
  version:  "4.9.197"
  name:     "sabayon-sources"

includes:
- /usr/portage/packages/.*
