steps:
- emerge -b =app-emulation/virtualbox-guest-additions-${PACKAGE_VERSION}
requires:
- category: "sys-kernel"
  version:  "4.9.152"
  name:     "linux-sabayon"
- category: "sys-kernel"
  version:  "4.9.152"
  name:     "sabayon-sources"

includes:
- /usr/portage/packages/.*
