steps:
- emerge -j  -t --nospinner -b =${GENTOO_CATEGORY}/tp_smapi-${GENTOO_VERSION}

- cd /usr/portage/packages/${GENTOO_CATEGORY}
- mv tp_smapi-${GENTOO_VERSION}.tbz2 tp_smapi-${PACKAGE_VERSION}.tbz2

env:
- "GENTOO_VERSION=0.43"
- "GENTOO_CATEGORY=app-laptop"
requires:
- category: "sys-kernel"
  version:  "5.3.7"
  name:     "linux-sabayon"
- category: "sys-kernel"
  version:  "5.3.7"
  name:     "sabayon-sources"

includes:
- /usr/portage/packages/.*

