steps:
- emerge -b =sys-fs/zfs-kmod-${PACKAGE_VERSION}
requires:
- category: "sys-kernel"
  version:  "4.19.42"
  name:     "linux-sabayon"
- category: "sys-kernel"
  version:  "4.19.42"
  name:     "sabayon-sources"

includes:
- /usr/portage/packages/.*
