steps:
- emerge -b =net-wireless/broadcom-sta-${PACKAGE_VERSION}
requires:
- category: "sys-kernel"
  version:  "4.19.55"
  name:     "linux-sabayon"
- category: "sys-kernel"
  version:  "4.19.55"
  name:     "sabayon-sources"

includes:
- /usr/portage/packages/.*
