steps:
- emerge -b =net-firewall/rtsp-conntrack-${PACKAGE_VERSION}
requires:
- category: "sys-kernel"
  version:  "4.19.31"
  name:     "linux-sabayon"
- category: "sys-kernel"
  version:  "4.19.31"
  name:     "sabayon-sources"

includes:
- /usr/portage/packages/.*
