steps:
- emerge -b =app-laptop/tp_smapi-${PACKAGE_VERSION}
requires:
- category: "sys-kernel"
  version:  "4.20.14"
  name:     "linux-sabayon"
- category: "sys-kernel"
  version:  "4.20.14"
  name:     "sabayon-sources"

includes:
- /usr/portage/packages/.*
