steps:
- emerge -j  -t --nospinner -b =${GENTOO_CATEGORY}/rtsp-conntrack-${GENTOO_VERSION}

- cd /usr/portage/packages/${GENTOO_CATEGORY}
- mv rtsp-conntrack-${GENTOO_VERSION}.tbz2 rtsp-conntrack-${PACKAGE_VERSION}.tbz2

env:
- "GENTOO_VERSION=4.18"
- "GENTOO_CATEGORY=net-firewall"
requires:
- category: "sys-kernel"
  version:  "4.9.193"
  name:     "linux-sabayon"
- category: "sys-kernel"
  version:  "4.9.193"
  name:     "sabayon-sources"

includes:
- /usr/portage/packages/.*

