steps:
- emerge -j  -t --nospinner -b =${GENTOO_CATEGORY}/bbswitch-${GENTOO_VERSION}

- cd /usr/portage/packages/${GENTOO_CATEGORY}
- mv bbswitch-${GENTOO_VERSION}.tbz2 bbswitch-${PACKAGE_VERSION}.tbz2

env:
- "GENTOO_VERSION=0.8-r2"
- "GENTOO_CATEGORY=sys-power"
requires:
- category: "sys-kernel"
  version:  "4.20.5"
  name:     "linux-sabayon"
- category: "sys-kernel"
  version:  "4.20.5"
  name:     "sabayon-sources"

includes:
- /usr/portage/packages/.*

