steps:
- source /etc/profile && emerge -j 3 -t --nospinner -b =${GENTOO_CATEGORY}/acpi_call-${GENTOO_VERSION}

- cd /usr/portage/packages/${GENTOO_CATEGORY}
- mv acpi_call-${GENTOO_VERSION}.tbz2 acpi_call-${PACKAGE_VERSION}.tbz2

env:
- "GENTOO_VERSION=3.17"
- "GENTOO_CATEGORY=sys-power"
requires:
- category: "sys-kernel"
  version:  "4.14.155"
  name:     "linux-sabayon"
- category: "sys-kernel"
  version:  "4.14.155"
  name:     "sabayon-sources"

includes:
- /usr/portage/packages/.*

