steps:
- emerge -j  -t --nospinner -b =${GENTOO_CATEGORY}/virtualbox-modules-${GENTOO_VERSION}

- cd /usr/portage/packages/${GENTOO_CATEGORY}
- mv virtualbox-modules-${GENTOO_VERSION}.tbz2 virtualbox-modules-${PACKAGE_VERSION}.tbz2

env:
- "GENTOO_VERSION=6.0.14"
- "GENTOO_CATEGORY=app-emulation"
requires:
- category: "sys-kernel"
  version:  "5.3.2"
  name:     "linux-sabayon"
- category: "sys-kernel"
  version:  "5.3.2"
  name:     "sabayon-sources"

includes:
- /usr/portage/packages/.*

