steps:
- source /etc/profile && emerge -j 3 -t --nospinner -b =${GENTOO_CATEGORY}/virtualbox-guest-additions-${GENTOO_VERSION}

- cd /usr/portage/packages/${GENTOO_CATEGORY}
- mv virtualbox-guest-additions-${GENTOO_VERSION}.tbz2 virtualbox-guest-additions-${PACKAGE_VERSION}.tbz2

env:
- "GENTOO_VERSION=6.0.14"
- "GENTOO_CATEGORY=app-emulation"
requires:
- category: "sys-kernel"
  version:  "5.4.3"
  name:     "linux-sabayon"
- category: "sys-kernel"
  version:  "5.4.3"
  name:     "sabayon-sources"

includes:
- /usr/portage/packages/.*

