steps:
- source /etc/profile && emerge -j 3 -t --nospinner -b =${GENTOO_CATEGORY}/wireguard-${GENTOO_VERSION}

- cd /usr/portage/packages/${GENTOO_CATEGORY}
- mv wireguard-${GENTOO_VERSION}.tbz2 wireguard-${PACKAGE_VERSION}.tbz2

env:
- "GENTOO_VERSION=0.0.20190406-r1"
- "GENTOO_CATEGORY=net-vpn"
requires:
- category: "sys-kernel"
  version:  "4.4.210"
  name:     "linux-sabayon"
- category: "sys-kernel"
  version:  "4.4.210"
  name:     "sabayon-sources"

includes:
- /usr/portage/packages/.*

