steps:
- emerge -j  -t --nospinner -b =${GENTOO_CATEGORY}/nvidia-drivers-${GENTOO_VERSION}

- cd /usr/portage/packages/${GENTOO_CATEGORY}
- mv nvidia-drivers-${GENTOO_VERSION}.tbz2 nvidia-drivers-${PACKAGE_VERSION}.tbz2

env:
- "GENTOO_VERSION=340.107-r1"
- "GENTOO_CATEGORY=x11-drivers"
requires:
- category: "sys-kernel"
  version:  "4.9.133"
  name:     "linux-sabayon"
- category: "sys-kernel"
  version:  "4.9.133"
  name:     "sabayon-sources"

includes:
- /usr/portage/packages/.*

