steps:
- emerge -b =net-vpn/wireguard-${PACKAGE_VERSION}
requires:
- category: "sys-kernel"
  version:  "4.14.134"
  name:     "linux-sabayon"
- category: "sys-kernel"
  version:  "4.14.134"
  name:     "sabayon-sources"

includes:
- /usr/portage/packages/.*
