steps:
- emerge -b =app-emulation/virtualbox-modules-${PACKAGE_VERSION}
requires:
- category: "sys-kernel"
  version:  "4.19.83"
  name:     "linux-sabayon"
- category: "sys-kernel"
  version:  "4.19.83"
  name:     "sabayon-sources"

includes:
- /usr/portage/packages/.*
