steps:
- emerge =${PACKAGE_CATEGORY}/${PACKAGE_NAME}-${PACKAGE_VERSION}
requires:
- category: "layer"
  version:  ">=0.1"
  name:     "build-sabayon-overlays"
- category: "layer"
  version:  ">=0.1"
  name:     "sabayon-overlay"
includes:
- /usr/portage/packages/.*
