steps:
- emerge -b =sys-fs/vhba-${PACKAGE_VERSION}
requires:
- category: "sys-kernel"
  version:  "4.9.153"
  name:     "linux-sabayon"
- category: "sys-kernel"
  version:  "4.9.153"
  name:     "sabayon-sources"

includes:
- /usr/portage/packages/.*
