steps:
- emerge -b =${GENTOO_CATEGORY}/broadcom-sta-${GENTOO_VERSION}

- cd /usr/portage/packages/${GENTOO_CATEGORY}
- mv broadcom-sta-${GENTOO_VERSION}.tbz2 broadcom-sta-${PACKAGE_VERSION}.tbz2

env:
- "GENTOO_VERSION=6.30.223.271-r6"
- "GENTOO_CATEGORY=net-wireless"
requires:
- category: "sys-kernel"
  version:  "4.14.160"
  name:     "linux-sabayon"
- category: "sys-kernel"
  version:  "4.14.160"
  name:     "sabayon-sources"

includes:
- /usr/portage/packages/.*

