steps:
- emerge -b =sys-power/bbswitch-${PACKAGE_VERSION}
requires:
- category: "sys-kernel"
  version:  "4.20.12"
  name:     "linux-sabayon"
- category: "sys-kernel"
  version:  "4.20.12"
  name:     "sabayon-sources"

includes:
- /usr/portage/packages/.*
